### ISSUE TITLE
Conditionally push NuGet package

### ISSUE THREAD

**Issue by StevenLiekens** [appveyor/website#100]
Is it possible to build multiple configurations (Debug / Release) and pack NuGet packages for all configurations but publish only Release packages?

The docs do not describe any way to do this. https://github.com/appveyor/website/blob/master/NJekyll/site/docs/deployment/nuget.md

**Comment by StevenLiekens** [comment]
Would this work?

````yaml
configuration:
- Debug
- Release
deploy:
- provider: NuGet
  on:
    configuration: Release
````

The `on` parameter is not documented.
