### ISSUE TITLE
can't upload artifact on my private Appveyor server

### ISSUE THREAD

**Issue by ArgoZhang** [appveyor/website#619]
hi, i have got the follow error message after build.
```
The requested service 'nuget (Appveyor.Deploy.IDeploymentProvider)' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
```
what can i do?
thanks for your help.
The appveyor server info
AppVeyor version (releases) 7.0.2126
SKU Community Edition

**Comment by FeodorFitsner** [comment]
Hi, are you configuring deployment in `appveyor.yml`? Make sure provider name is written exactly as `NuGet`, not `nuget`. Provider names are case-sensitive. Hope that helps.

**Comment by ArgoZhang** [comment]
> Hi, are you configuring deployment in `appveyor.yml`? Make sure provider name is written exactly as `NuGet`, not `nuget`. Provider names are case-sensitive. Hope that helps.

thanks for your reply
this is my appveyor.yml
```
version: 1.0.{build}
build_cloud: Process
max_jobs: 1
image: Visual Studio 2017
clone_depth: 1
build_script:
- ps: >-
    dotnet build Bootstrap.Admin

    dotnet publish Bootstrap.Admin -c Release
test: off
artifacts:
- path: Bootstrap.Admin\bin\release\netcoreapp2.2\publish\
```

when uploading artifacts will occurs the error
Uploading artifacts...
[1/1] Bootstrap.Admin\bin\Release\netcoreapp2.2\publish.zip (12,805,870 bytes)...
**Error uploading artifact the storage: Artifact not found or access denied.**

how fix this error?
configuration some env?

**Comment by FeodorFitsner** [comment]
Will take a look, thanks for sharing the yaml.

Regarding the error in the original post (`The requested service 'nuget (Appveyor.Deploy.IDeploymentProvider)' has not been registered`) - how/where do you get it?

**Comment by ArgoZhang** [comment]
in another project.
```
version: 1.0.{build}
max_jobs: 2
image: Visual Studio 2017
clone_depth: 1
environment:
  majorVersion: 2
  minorVersion: 2
  patchVersion: 0
  masterVersion: $(majorVersion).$(minorVersion).$(patchVersion)
  devVersion: $(majorVersion).$(minorVersion).$(APPVEYOR_BUILD_NUMBER)-beta
  nugetUrl: https://app.sdgxgz.com/nuget/appveyor-kd558oo19384/api/v2/package
  nugetKey: 71u3f5t82euwe4wjngw9ocir
build_script:
- ps: >-
    dotnet build Longbow
    dotnet publish Longbow -c Release
    dotnet pack Longbow -c Release
deploy:
- provider: NuGet
  server: https://app.sdgxgz.com/nuget/appveyor-kd558oo19384
  api_key:
    secure: G2VbpZPENcjEZP2yCUv/eS69fdQksFXKoxPOMHSS2zk=
  skip_symbols: true
```
i will get the following error when running to Deployment phase
```
Deploying artifacts using NuGet provider
The requested service 'nuget (Appveyor.Deploy.IDeploymentProvider)' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
```

BTW: I notice that i have not config nothing for Artifacts. because Artifacts always wrong too :)
