### ISSUE TITLE
Account Nuget feed does not work

### ISSUE THREAD

**Issue by ArgoZhang** [appveyor/website#622]
hi, after install the latest version AppVeyor version 7.0.2150 I found that account NuGet feed does not work now. it work fine in previous version.
share my AppVeyor.yml
```
version: 1.0.{build}
max_jobs: 2
image: Visual Studio 2017
clone_depth: 1
environment:
  majorVersion: 2
  minorVersion: 2
  patchVersion: 0
  masterVersion: $(majorVersion).$(minorVersion).$(patchVersion)
  devVersion: $(majorVersion).$(minorVersion).$(APPVEYOR_BUILD_NUMBER)-beta
  nugetUrl: https://app.sdgxgz.com/nuget/appveyor-kd558oo19384/api/v2/package
  nugetKey: XXXXXXXXXXXXXXXXXXX
build_script:
- ps: >-
    dotnet build Longbow
    dotnet publish Longbow -c Release
    dotnet pack Longbow -c Release /p:Version=2.2.31
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://app.sdgxgz.com/nuget/appveyor-kd558oo19384
  api_key:
    secure: XXXXXXXXXXXXXXXXXX
  skip_symbols: true
```
repo steps as below
1. run build in appveyor
```
Collecting artifacts...
Found artifact 'Longbow\bin\Release\Longbow.2.2.31.nupkg' matching '**\*.nupkg' path
Uploading artifacts...
[1/1] Longbow\bin\Release\Longbow.2.2.31.nupkg (28,197 bytes)...OK
Deploying artifacts using NuGet provider
Publishing Longbow.2.2.31.nupkg to https://app.sdgxgz.com/nuget/appveyor-kd558oo19384...OK
Total packages published: 1
Build completed
```
as show. it build success.
2. configurate nuget source in vs2019&vs2017
add new package sources in Nuget Package Manager
source: https://app.sdgxgz.com/nuget/appveyor-kd558oo19384
3. right click project
4. choose the "Manager Nuget Packages..." context menu
5. package source choose AppVeyor account feed.
6. refresh in the browse tab
no item shown in the list.
