### ISSUE TITLE
Unable to run Invoke-SqlCmd against SQL Server 2016

### ISSUE THREAD

**Issue by Beakerboy** [appveyor/website#738]
I have the simplest yml file possible:

```
services:
  - mssql2016
image:
  - Visual Studio 2017
install:
  - ps: Start-Service 'MSSQL$SQL2016' | out-null
  - ps: Invoke-Sqlcmd -Username sa -Password "Password12!" -Query "CREATE DATABASE mydrupalsite"
```

The error message is:
```
Invoke-Sqlcmd : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
```
