### ISSUE TITLE
.NET 8 Preview Edition Enablement

### ISSUE THREAD

**Issue by mikependon** [appveyor/website#845]
.NET 8 Preview has been made available to the public. I started to migrate my OSS library as well to target the `net8.0` TFM as well.
Here is the link to the announcement: https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-1/

Currently, the site is not supporting it, but it sounds to me an important one so the public can start test and integrate in advance.

![image](https://user-images.githubusercontent.com/591015/225250903-62be9608-a217-4349-b22f-bd15572c0732.png)

Would it be possible to support this and thanks in advance.

**Comment by FeodorFitsner** [comment]
You can easily install .NET 8 Preview during the build with this simple script added to your `appveyor.yml`:

```yaml
install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '8.0.100-preview.2.23157.25' -InstallDir "$env:ProgramFiles\dotnet"
```

[Full gist](https://gist.github.com/FeodorFitsner/c62c323dee76b6c116e6ea699770f587#file-appveyor-yml-L4-L6).

**Comment by mikependon** [comment]
Thanks for this trick! It works actual as it builds the project and went passthrough to the next builds.

![image](https://user-images.githubusercontent.com/591015/225736096-64733da9-9fc3-4539-96df-78e8350563dd.png)

However, it then suddenly failing when the output binaries has been copied over and rebuilt before the actual test executions.

![image](https://user-images.githubusercontent.com/591015/225735971-318d9279-3909-4bd2-8b56-c0d536e5812e.png)

Suspecious as well of why I can see the log below, it sounds to me that the path is not correct. If it, then it sounds to me that the .NET 8 version is not instaled on the Node 1.

```
Project "C:\projects\repodb-yf1cx\RepoDb.Core\RepoDb.Tests\RepoDb.UnitTests\RepoDb.UnitTests.csproj" (1) is building "C:\projects\repodb-yf1cx\RepoDb.Core\RepoDb.Tests\RepoDb.UnitTests\RepoDb.UnitTests.csproj" (1:4) on node 1 (Build target(s)).
C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [C:\projects\repodb-yf1cx\RepoDb.Core\RepoDb.Tests\RepoDb.UnitTests\RepoDb.UnitTests.csproj::TargetFramework=net8.0]
Done Building Project "C:\projects\repodb-yf1cx\RepoDb.Core\RepoDb.Tests\RepoDb.UnitTests\RepoDb.UnitTests.csproj" (Build target(s)) -- FAILED.
Done Building Project "C:\projects\repodb-yf1cx\RepoDb.Core\RepoDb.Tests\RepoDb.UnitTests\RepoDb.UnitTests.csproj" (default targets) -- FAILED.
```

Here is the log file that contains the error. (File: [log.txt](https://github.com/appveyor/website/files/10995340/log.txt))
Link: https://ci.appveyor.com/project/mikependon/repodb-yf1cx

**Comment by FeodorFitsner** [comment]
Try using `dotnet msbuild` to build `RepoDb.UnitTests.csproj` directly.

**Comment by mikependon** [comment]
Where is that in the YAML? Was it the `build:` section?

```
version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2022
configuration: Release
platform: Any CPU
install:
- ps: >-
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
        & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '8.0.100-preview.2.23157.25' -InstallDir "$env:ProgramFiles\dotnet"
before_build:
- cmd: dotnet restore RepoDb.Core\RepoDb.Tests\RepoDb.UnitTests\RepoDb.UnitTests.csproj
build:
  project: RepoDb.Core\RepoDb.Tests\RepoDb.UnitTests\RepoDb.UnitTests.csproj
  verbosity: normal
test_script:
- cmd: vstest.console /logger:Appveyor RepoDb.Core\RepoDb.Tests\RepoDb.UnitTests\bin\Release\net7.0\RepoDb.UnitTests.dll
```
